tasks:
  - init: cd .gitpod && docker-compose pull
  - command: cd .gitpod && docker-compose up

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

image:
  file: .gitpod/Dockerfile
